service: project-template-backend

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  #Note on Dynamo Tables, you should setup permissions per end point for best practice
  role: UserRole
  environment:
    STAGE: ${self:custom.stage}

#Note on Dynamo Tables, you should setup permissions per end point for best practice
functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
#  uncomment for dynamo tables iam
- ${file(src/database/dynamodb/dynamo-serverless-resources.yml)}
- ${file(src/database/dynamodb/dynamo-iam.yml)}